#!/bin/bash
#by viniciusecortez
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
git_status(){
     git status 2> /dev/null
}

export before_PS1=$PS1
which_branch(){
     if [ -d .git ] && [ -z $(parse_git_branch) ] ; then
          echo '!(uncommited)'     
     elif [ -d .git ] ; then
          echo $(parse_git_branch)
     fi
}

color_status(){
     #cores
     local verde="\033[1;32m"
     local vermelho="\033[1;31m"
     local amarelo="\033[33m"
     # opcoes
     local untracked=$( git_status | grep Untracked ) 
     local modified=$( git_status | grep modified )
     local to_be_commited=$(git status | grep "to be committed")

     if [ ! -z "$to_be_commited" ] ; then 
          echo -e $amarelo
     elif [ ! -z "$untracked" ] || [ ! -z "$modified" ] ; then
          echo -e $vermelho
     else
          echo -e $verde
     fi
     
}

export PS1="\[\033[01;95m\]\u@\h\[\033[00m\]:\[\033[94m\]\w\[\$(color_status)\] \$(which_branch) \[\033[00m\]"

if [ $(whoami) == 'root' ] ; then
     export PS1="$PS1\n# "
else
     export PS1="$PS1\n$ "
fi

